[tool.poetry]
name = "realm-e2e"
version = "0.1.0"
description = "End-to-end tests for realm"
authors = ["Or Levi <orlevi128@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.1"
realm = {path = "../../packages/realm"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
