site_name: Realm
site_description: Realm - Multi-Project Python Build Tool
theme:
  name: material
  features:
    - content.code.copy

plugins:
    - search
    - awesome-pages

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
