name: build

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dev-dependencies
        run: |
          pip install -U pip
          pip install poetry poethepoet
          poetry install
      - name: Lint
        run: poe lint

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v2
      - name: Fetch master
        run: git fetch origin master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install poetry poethepoet
          poetry install
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ matrix.os == 'windows-latest' }}
      - name: Run tests
        run: poe test
      - name: Coverage report
        run: poetry run coverage report
